// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReactUse = require("react-use");
var Util$ReactHooksTemplate = require("../Util.bs.js");
var Library$ReactHooksTemplate = require("../Library/Library.bs.js");

require("./Player.css");

function Player(Props) {
  var tracks = Props.tracks;
  var match = React.useReducer((function (state, $$event) {
          return /* record */[
                  /* status */state[/* status */0],
                  /* activeTrackIndex */$$event[0]
                ];
        }), /* record */[
        /* status : Stopped */0,
        /* activeTrackIndex */undefined
      ]);
  var send = match[1];
  var match$1 = ReactUse.useAudio({
        src: "/Users/alavkx/Projects/reasonml-test/static/Skepta - Nasty (Kelly Dean Bootleg Remix).wav",
        autoPlay: false
      });
  var controls = match$1[2];
  var playerState = match$1[1];
  return React.createElement(React.Fragment, undefined, React.createElement(Library$ReactHooksTemplate.make, {
                  tracks: tracks,
                  playTrack: (function (i) {
                      return Curry._1(send, /* PlayTrack */[i]);
                    })
                }), React.createElement("section", {
                  "aria-label": "player",
                  onKeyDown: (function (e) {
                      var match = e.key;
                      switch (match) {
                        case "ArrowLeft" : 
                            return Curry._1(controls[/* seek */5], playerState[/* time */1] - 5.0);
                        case "ArrowRight" : 
                            return Curry._1(controls[/* seek */5], playerState[/* time */1] + 5.0);
                        default:
                          return /* () */0;
                      }
                    })
                }, React.createElement("div", {
                      className: "controls"
                    }, match$1[0], React.createElement("button", {
                          onClick: (function (_e) {
                              return Curry._1(controls[/* pause */1], /* () */0);
                            })
                        }, Util$ReactHooksTemplate.str("Pause")), React.createElement("button", {
                          onClick: (function (_e) {
                              Curry._1(controls[/* play */0], /* () */0);
                              return /* () */0;
                            })
                        }, Util$ReactHooksTemplate.str("Play")), React.createElement("button", {
                          onClick: (function (_e) {
                              return Curry._1(controls[/* mute */2], /* () */0);
                            })
                        }, Util$ReactHooksTemplate.str("Mute")), React.createElement("button", {
                          onClick: (function (_e) {
                              return Curry._1(controls[/* unmute */3], /* () */0);
                            })
                        }, Util$ReactHooksTemplate.str("Un-mute")), React.createElement("input", {
                          max: "1",
                          min: 0,
                          step: 0.01,
                          type: "range",
                          onChange: (function (e) {
                              return Curry._1(controls[/* volume */4], e.target.value);
                            })
                        }))));
}

var make = Player;

exports.make = make;
/*  Not a pure module */
