// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Util$ReactHooksTemplate = require("./Util.bs.js");
var Player$ReactHooksTemplate = require("./Player/Player.bs.js");

require("./App.css");

var persistedTracks = /* array */[
  /* record */[
    /* name */"007",
    /* artist */"Kromestar",
    /* src */"/Users/alavkx/Projects/reasonml-test/static/Skepta - Nasty (Kelly Dean Bootleg Remix).wav"
  ],
  /* record */[
    /* name */"008",
    /* artist */"Kromestar",
    /* src */"/Users/alavkx/Projects/reasonml-test/static/Skepta - Nasty (Kelly Dean Bootleg Remix).wav"
  ],
  /* record */[
    /* name */"009",
    /* artist */"Kromestar",
    /* src */"/Users/alavkx/Projects/reasonml-test/static/Skepta - Nasty (Kelly Dean Bootleg Remix).wav"
  ],
  /* record */[
    /* name */"0010",
    /* artist */"Kromestar",
    /* src */"/Users/alavkx/Projects/reasonml-test/static/Skepta - Nasty (Kelly Dean Bootleg Remix).wav"
  ]
];

function Index$App(Props) {
  var match = React.useState((function () {
          return undefined;
        }));
  var setTracks = match[1];
  var tracks = match[0];
  React.useEffect((function () {
          var timeoutId = setTimeout((function (param) {
                  return Curry._1(setTracks, (function (param) {
                                return persistedTracks;
                              }));
                }), 500);
          return (function (param) {
                    clearTimeout(timeoutId);
                    return /* () */0;
                  });
        }), /* array */[setTracks]);
  if (tracks !== undefined) {
    return React.createElement(Player$ReactHooksTemplate.make, {
                tracks: tracks
              });
  } else {
    return Util$ReactHooksTemplate.str("Booting up the most incredible experience of your life...");
  }
}

var App = /* module */[
  /* persistedTracks */persistedTracks,
  /* make */Index$App
];

ReactDOMRe.renderToElementWithId(React.createElement(Index$App, { }), "root");

exports.App = App;
/*  Not a pure module */
